### ISSUE TITLE
use 100% of the container.

### ISSUE THREAD

**Issue by cesarpe** [LeoNero/react-img-zoom#20]
Hello,
I needed to use 100% of the container so that it can be applied to different screen sizes and the modification has remained as follows:
I changed the index.js file

  const {
       height,
       img,
       transitionTime,
       width = (width==- 1? '100%': width + 'px'), // if it is -1, use 100% of the container
     } = props

    this.outerDivStyle = {
       height: `$ {height} px`,
       width: width,
       // width: `$ {width} px`,
       overflow: 'hidden',
     }

Mode of use:
<Zoom key = {this.state.key}
             img = {this.state.imgcur}
             zoomScale = {3}
             height = {600}
             width = {- 1} // use 100% of the container
             transitionTime = {0.5}
  />

**Comment by LeoNero** [comment]
Hi @cesarpe ! I am going to create an issue so that I can add the option to use 100% of the container in a next update. In the issue, I'll write a proposal of interface a little bit different than what you did. If you could take a look at the issue and give your opinion on the interface proposed, I would appreciate :)

**Comment by cesarpe** [comment]
Hello Leonardo, happy to help.
